name: jobsfinder

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - chrome
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234r
      - POSTGRES_HOST=db
      - SELENIUM_HOST=chrome
    networks:
      - app_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234r
    ports:
      - "5432:5432"
    networks:
      - app_network

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=rayen08yako@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234r
    depends_on:
      - db
    networks:
      - app_network

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
