version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - chrome
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234r
      - POSTGRES_HOST=db
      - SELENIUM_HOST=chrome

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=jobs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234r

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"

volumes:
  postgres_data:
