# Generated by Django 6.0.3 on 2026-03-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_joblisting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='is_relevant',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='nlp_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
