# Generated by Django 6.0.4 on 2026-04-19 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_joblisting_extracted_skills_joblisting_is_relevant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='is_relevant_human_label',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='labeled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
