# Generated by Django 5.2.6 on 2026-04-22 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scraping", "0004_joblisting_is_relevant_human_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable model name, e.g. 'RelevanceClassifier v2'", max_length=255)),
                ('model_type', models.CharField(choices=[('classifier', 'Relevance Classifier'), ('ner', 'Skills Extractor (NER)')], help_text='The type of model (classifier or NER)', max_length=20)),
                ('version', models.CharField(help_text="Semantic version string, e.g. '1.0.0'", max_length=50)),
                ('huggingface_model_id', models.CharField(help_text="HuggingFace model identifier, e.g. 'distilbert-base-uncased'", max_length=255)),
                ('accuracy', models.FloatField(blank=True, help_text='Model accuracy on the evaluation set (0.0 - 1.0)', null=True)),
                ('f1_score', models.FloatField(blank=True, help_text='Model F1 score on the evaluation set (0.0 - 1.0)', null=True)),
                ('training_date', models.DateTimeField(blank=True, help_text='When this model version was trained', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this model version is currently active')),
                ('notes', models.TextField(blank=True, default='', help_text='Free-form notes about this model version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ML Model Metadata',
                'verbose_name_plural': 'ML Model Metadata',
                'ordering': ['-created_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_used', models.CharField(help_text='Identifier of the model used for this inference', max_length=255)),
                ('model_version', models.CharField(default='1.0.0', help_text='Version of the model used', max_length=50)),
                ('inference_type', models.CharField(choices=[('classification', 'Classification'), ('ner', 'Named Entity Recognition'), ('full', 'Full Pipeline')], default='full', help_text='Type of inference performed', max_length=20)),
                ('is_relevant', models.BooleanField(blank=True, help_text='Classification result: relevant or not', null=True)),
                ('relevance_score', models.FloatField(blank=True, help_text='Confidence score (0.0 - 1.0)', null=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list, help_text='Skills extracted by NER')),
                ('processing_time_ms', models.FloatField(blank=True, help_text='Time taken for inference in milliseconds', null=True)),
                ('success', models.BooleanField(default=True, help_text='Whether inference completed successfully')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if inference failed')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this inference was performed')),
                ('job_listing', models.ForeignKey(help_text='The job listing that was processed', on_delete=django.db.models.deletion.CASCADE, related_name='inference_logs', to='scraping.joblisting')),
            ],
            options={
                'verbose_name': 'Inference Log',
                'verbose_name_plural': 'Inference Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['job_listing', '-timestamp'], name='deep_learni_job_lis_b97860_idx'), models.Index(fields=['model_used'], name='deep_learni_model_u_561532_idx'), models.Index(fields=['-timestamp'], name='deep_learni_timesta_77b7ae_idx')],
            },
        ),
    ]
